[versions]
agp = "8.9.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
exp4j = "0.4.8"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
exp4j = { group = "net.objecthunter", name = "exp4j", version.ref = "exp4j" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

